const btn = document.querySelector('.slider')
const darkTexts = document.querySelector('.dark1')
const one = document.querySelector('.one')
const two = document.querySelector('.two')
const three = document.querySelector('.three')
const four = document.querySelector('.four')
const number1 = document.querySelector('.number1')
const number2 = document.querySelector('.number2')
const number3 = document.querySelector('.number3')
const number4 = document.querySelector('.number4')
const today = document.querySelector('.p')
const h1 = document.querySelector('.h1')
const over1 = document.querySelector('.first')
const over2 = document.querySelector('.second')
const over3 = document.querySelector('.third')
const over4 = document.querySelector('.fourth')
const over5 = document.querySelector('.fifth')
const over6 = document.querySelector('.sixth')
const over7 = document.querySelector('.seventh')
const over8 = document.querySelector('.eighth')


const changeTheme = () => {
	darkTexts.classList.toggle('darkColor')
	document.querySelector('body').classList.toggle('body-color')
    one.classList.toggle('bg-card')
    two.classList.toggle('bg-card')
    three.classList.toggle('bg-card')
    four.classList.toggle('bg-card')
    number1.classList.toggle('light-theme-text')
    number2.classList.toggle('light-theme-text')
    number3.classList.toggle('light-theme-text')
    number4.classList.toggle('light-theme-text')
    today.classList.toggle('green')
    h1.classList.toggle('gray')
    over1.classList.toggle('bg-card')
    over2.classList.toggle('bg-card')
    over3.classList.toggle('bg-card')
    over4.classList.toggle('bg-card')
    over5.classList.toggle('bg-card')
    over6.classList.toggle('bg-card')
    over7.classList.toggle('bg-card')
    over8.classList.toggle('bg-card')
}

btn.addEventListener('click', changeTheme)
